# Generated by Django 2.2.6 on 2024-01-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_laptops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
    ]
