# Generated by Django 2.2.6 on 2024-01-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20240105_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='./templates/books/IMG_2181.jpg', upload_to='image'),
        ),
    ]
