# Generated by Django 2.2.6 on 2024-01-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20240105_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Book')),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
            bases=('books.book',),
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Book')),
                ('file_format', models.CharField(max_length=50)),
            ],
            bases=('books.book',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='templates/books/IMG_2181.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='books.Genre'),
        ),
    ]
