# Generated by Django 2.2.6 on 2024-01-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20240105_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Funny', 'Funny'), ('Kids', 'Kids')], max_length=100),
        ),
    ]
