# Generated by Django 2.2.6 on 2024-01-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20240105_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='book_ptr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.DeleteModel(
            name='AudioBook',
        ),
        migrations.DeleteModel(
            name='EBook',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
