# Generated by Django 2.2.6 on 2024-01-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imagePath',
            field=models.CharField(default='/', max_length=1000),
        ),
    ]
