# Generated by Django 2.2.6 on 2024-01-07 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20240106_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='generated_isbn',
            field=models.CharField(default='123456', editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^\\d{1,25}$', 'ISBN must contain only numbers.')]),
        ),
    ]
