# Generated by Django 2.2.6 on 2024-01-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20240107_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='generated_isbn',
        ),
    ]
